### ISSUE TITLE
Remove unnecessary lines from falcon config ctmpl 

### ISSUE THREAD

**Issue by samanehsan** [HumanCellAtlas/secondary-analysis-deploy#21]
The `$liraSecret` and `$hmac_keys` variables are not used in `falcon-config.json.ctmpl` so those `with` conditionals can be removed:
https://github.com/HumanCellAtlas/secondary-analysis-deploy/blob/integration/config_files/falcon-config.json.ctmpl#L2-L3

**Comment by rhiananthony** [comment]
Fixed
