### ISSUE TITLE
Question about rendering ctmpl files

### ISSUE THREAD

**Issue by samanehsan** [HumanCellAtlas/secondary-analysis-deploy#23]
What is the difference between these two ways of rendering the falcon config files? 

This one is used in the gitlab deploy script: https://github.com/HumanCellAtlas/secondary-analysis-deploy/blob/integration/gitlab/deploy_falcon.sh#L14
```
sh "${DEPLOY_DIR}/render-ctmpls.sh" -k "${CONFIG_DIR}/${FALCON_CONFIG_FILE}.ctmpl"
```
and this one is used in the jenkins deploy script: https://github.com/HumanCellAtlas/secondary-analysis-deploy/blob/integration/jenkins/deploy_falcon.sh#L16

```
docker run -i --rm \
               -v "${VAULT_READ_TOKEN_PATH}":/root/.vault-token \
               -v "${PWD}":/working \
               -e ENVIRONMENT="${ENVIRONMENT}" \
               --privileged \
               broadinstitute/dsde-toolbox:ra_rendering \
               /usr/local/bin/render-ctmpls.sh \
               -k "${DOCKER_CONFIG_DIR}/config.sh.ctmpl"
```

**Comment by rhiananthony** [comment]
Gitlab is running on a docker image, which contains all of the packages necessary to do the rendering. Jenkins runs on the server and therefore needs the docker image to render the files.
